/**
 * NewStarSports — Supabase Database Types
 *
 * This file will be auto-generated by running:
 *   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > packages/db/types.ts
 *
 * For now, this is a placeholder with the expected structure.
 * Once the Supabase project is created and tables are set up,
 * regenerate this file to get full type safety.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          locale_preference: "en" | "ar";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          locale_preference?: "en" | "ar";
        };
        Update: {
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          locale_preference?: "en" | "ar";
        };
      };
      products: {
        Row: {
          id: string;
          name_en: string;
          name_ar: string;
          slug: string;
          short_description_en: string;
          short_description_ar: string;
          description_en: string;
          description_ar: string;
          status: "draft" | "published" | "archived";
          price_kwd: number;
          compare_at_price_kwd: number | null;
          cost_price_kwd: number | null;
          category_id: string | null;
          brand_id: string | null;
          min_age: number;
          max_age: number | null;
          safety_warnings_en: string;
          safety_warnings_ar: string;
          kucas_certificate: string;
          kucas_expiry: string;
          country_of_origin: string;
          hs_code_6: string;
          gcc_tariff_12: string;
          weight_grams: number;
          length_cm: number;
          width_cm: number;
          height_cm: number;
          is_new_arrival: boolean;
          is_best_seller_override: boolean;
          is_homepage_featured: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["products"]["Row"], "id" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["products"]["Insert"]>;
      };
      categories: {
        Row: {
          id: string;
          name_en: string;
          name_ar: string;
          slug: string;
          parent_id: string | null;
          image_url: string | null;
          is_homepage_pinned: boolean;
          homepage_order: number | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["categories"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
      };
      brands: {
        Row: {
          id: string;
          name_en: string;
          name_ar: string;
          slug: string;
          logo_url: string | null;
          is_featured: boolean;
          display_order: number | null;
          created_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["brands"]["Row"], "id" | "created_at">;
        Update: Partial<Database["public"]["Tables"]["brands"]["Insert"]>;
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string;
          status: "pending" | "confirmed" | "processing" | "shipped" | "delivered" | "cancelled" | "refunded";
          payment_status: "pending" | "confirmed" | "failed" | "refunded";
          payment_method: string;
          transaction_id: string | null;
          subtotal_kwd: number;
          shipping_kwd: number;
          discount_kwd: number;
          total_kwd: number;
          coupon_code: string | null;
          shipping_address: Json;
          customer_name: string;
          customer_email: string;
          customer_phone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["orders"]["Row"], "id" | "order_number" | "created_at" | "updated_at">;
        Update: Partial<Database["public"]["Tables"]["orders"]["Insert"]>;
      };
      settings: {
        Row: {
          key: string;
          value: Json;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          key: string;
          value: Json;
        };
        Update: {
          value?: Json;
          updated_by?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
